services:
  ros2-humble:
    image: tiryoh/ros2-desktop-vnc:humble-arm64
    container_name: ros2-humble-mac
    ports:
      - "6080:6080"      # VNC Web
      - "10000:10000"    # ROS2通信
      - "2222:22"        # SSH
      - "8888:8888"      # Jupyter
      - "8000:8000"      # FastAPI
    volumes:
      - ~/ros2_ws:/home/ubuntu/ros2_ws:cached  # ワークスペース共有
      - ~/.ssh:/home/ubuntu/.ssh:ro              # SSH鍵（読み取り専用）
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_LOCALHOST_ONLY=0
      - RMW_FASTRTPS_USE_QOS_FROM_XML=0
      - DISPLAY=:0
    shm_size: 1024m
    restart: unless-stopped
    networks:
      - ros2-network
    # SSHサーバー起動とsupervisord起動
    command: >
      bash -c "
        sudo service ssh start &&
        sudo service dbus start &&
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "

networks:
  ros2-network:
    driver: bridge
